name: build
on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

jobs:
  lint:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
          java-package: jdk
          cache: 'maven'
      - name: spotless:check
        run: mvn --batch-mode --no-transfer-progress spotless:check
  build_deploy:
    permissions:
      contents: write
    name: Build natives libraries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
          java-package: jdk
          cache: 'maven'
      - name: Ensure snapshot
        run: |
          res=mvn help:evaluate -Dexpression=project.version -q -DforceStdout
          if [[ $res == *"SNAPSHOT"* ]]
          then
            echo "Build reserved to non snapshot version"
            exit 1
          fi
      - name: Prepare GPG sign
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          openssl aes-256-cbc -K ${{ secrets.ENCRYPTED_KEY }} -iv ${{ secrets.ENCRYPTED_IV }} -in ./scripts/private.key.enc -out /tmp/private.key -d
          gpg --version
          gpg --batch --import /tmp/private.key
          rm /tmp/private.key
      - name: Deploy version
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        if: startsWith(github.ref, 'refs/tags/')
        run: mvn --batch-mode --no-transfer-progress clean deploy -P release

